extends:
  - airbnb-base
  - plugin:prettier/recommended
env:
  node: true
parser: typescript-eslint-parser
parserOptions:
  ecmaVersion: 7
  sourceType: module
  ecmaFeatures:
    modules: true
plugins:
  - import
  - typescript
  - prettier
  - security
rules:
  strict: 0
  object-curly-spacing:
    - error
    - always

  # Follow up: https://github.com/eslint/typescript-eslint-parser/issues/416
  no-undef: 0
  no-use-before-define: 0
  no-restricted-globals: 0

  import/extensions: 0
settings:
  import/resolver:
    node:
      extensions:
        - .ts
        - .tsx
        - .d.ts
        - .js
        - .json

  import/parsers:
    typescript-eslint-parser:
      - .ts
